spring:
    servlet:
        multipart:
            max-file-size: 104857600
            max-request-size: 10485760
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
    datasource:
        url: jdbc:oracle:thin:@mcjang.iptime.org:1521:XE
        driver-class-name: oracle.jdbc.driver.OracleDriver
        username: ATEAM
        password: ateam
    mail:
        host: smtp.gmail.com
        port: 587
        username: ananec.dot@gmail.com
        password: lwwi wnrd mhdy kdai
        default-encoding: utf-8
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        
mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:com/ktdsuniversity/edu/**/dao/mapper/*.xml

# 파일 업로드 커스텀 설정 
app:
    # 파일 업로드 정책 관련 설정.
    multipart: 
        #업로드한 파일이 저장한 위치
        base-dir: C:/uploadFiles
        #파일명 난독화 관련 설정
        obfuscation:
            #난독화 사용 여부
            enable: true
            #파일명에서 확장자를 숨길 것인지에 대한 설정.
            hide-ext:
                enable: true
    oauth:
        kakao:
            access-token:
                url: https://kauth.kakao.com/oauth/token
                client-id: 2a9927f831835710fa3d3d37b078389c
                redirect-url: http://localhost:8080/member/kakaoLogin
            user-info:
                url: https://kapi.kakao.com/v2/user/me
            logout:
                url: https://kapi.kakao.com/v1/user/logout
        naver:
            access-token:
                url: https://nid.naver.com/oauth2.0/token
                client-id: ePAK2QDzEMghBxsqTuce
                client-secret: Fjfxbj04YU
                redirect-url: http://localhost:8080/member/naverLogin
            user-info:
                url: https://openapi.naver.com/v1/nid/me
        google:
            access-token:
                url: https://oauth2.googleapis.com/token
                client-id: 595210277098-t430mu7sj0n7dkl8ji1usbuke043tgvv.apps.googleusercontent.com
                client-secret: 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
                redirect-url: http://localhost:8080/member/googleLogin
            user-info: 
                url: https://www.googleapis.com/userinfo/v2/me
                
---
spring:
    config:
        activate:
            on-profile: prod

app:
    oauth:
        kakao:
            access-token:
                client-id: 2a9927f831835710fa3d3d37b078389c
                redirect-url: http://mcjang.iptime.org:8080/member/kakaoLogin
        naver:
            access-token:
                client-id: ePAK2QDzEMghBxsqTuce
                client-secret: Fjfxbj04YU
                redirect-url: http://mcjang.iptime.org:8080/member/naverLogin
        google:
            access-token:
                client-id: 595210277098-t430mu7sj0n7dkl8ji1usbuke043tgvv.apps.googleusercontent.com
                client-secret: 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
                redirect-url: http://localhost.org:8080/member/googleLogin
